---
apiVersion: hub.traefik.io/v1alpha1
kind: APIPlan
metadata:
  name: httpbin-plan
spec:
  title: "Standard Plan"
  description: "**Standard Plan with rate limits and quotas**"
  rateLimit:
    limit: 1
    period: 1s
  quota:
    limit: 10000
    period: 750h