---
apiVersion: hub.traefik.io/v1alpha1
kind: ManagedSubscription
metadata:
  name: httpbin-managed-subscription
spec:
  applications:
    - appId: "httpbin-app-1"
    - appId: "httpbin-app-2"
  apiBundles:
    - name: httpbin-bundle
  apiPlan:
    name: httpbin-plan
  weight: 100