---
apiVersion: hub.traefik.io/v1alpha1
kind: APIPortal
metadata:
  name: httpbin-portal
  namespace: traefik
spec:
  title: "HTTPBin Portal"
  description: "API documentations"
  trustedUrls:
    - "http://localhost:9903"
  ui:
    logoUrl: https://traefik.io/favicon.png
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: httpbin-portal-ingress
  namespace: traefik
  annotations:
    hub.traefik.io/api-portal: httpbin-portal
spec:
  routes:
  - match: Host(`localhost`)
    kind: Rule
    services:
    - name: apiportal
      port: 9903